### ISSUE TITLE
Multiple UPSTREAM_DNS via docker-compose doesn't work

### ISSUE THREAD

**Issue by DragonQ** [lancachenet/sniproxy#13]
The README says multiple upstream DNS servers can be defined via:

`-e UPSTREAM_DNS="1.1.1.1 1.0.0.1"`

However, whenever I try to define multiple servers in the UPSTREAM_DNS environment variable, the `lancachenet/sniproxy` docker container exits with error code 1. I've tried separating using a space (as `lancachenet/monolithic` uses) and separating using a semi-colon (as `lancachenet/lancache-dns` uses) but neither works. The error is:

```
lancache-sniproxy      | 2020-01-03 18:11:33 error parsing /etc/sniproxy.conf at 84 near:
lancache-sniproxy      | 2020-01-03 18:11:33  85        er "1.1.1.1 1.0.0.1"
lancache-sniproxy      | 2020-01-03 18:11:33  101               mode ipv4_only
lancache-sniproxy      | 2020-01-03 18:11:33  103       }
lancache-sniproxy      | 2020-01-03 18:11:33  104
lancache-sniproxy      | 2020-01-03 18:11:33  117       access_log {
lancache-sniproxy      | Unable to load /etc/sniproxy.conf
lancache-sniproxy      | Usage: sniproxy [-c <config>] [-f] [-n <max file descriptor limit>] [-V]
```

My docker-compose file looks like this:

```
version: '3.7'
services:
    lancache-monolithic:
        container_name: lancache
        image: 'lancachenet/monolithic:latest'
        restart: unless-stopped
        volumes:
            - '/data/cache:/data/cache'
            - '/data/logs:/data/logs'
        ports:
            - '${LANCACHE_IP}:80:80'
        environment:
            - UPSTREAM_DNS=${DNS_SERVERS}
            - CACHE_MEM_SIZE=${CACHE_MEM_SIZE}
            - CACHE_DISK_SIZE=${CACHE_DISK_SIZE}
    sniproxy:
        container_name: lancache-sniproxy
        image: 'lancachenet/sniproxy:latest'
        restart: unless-stopped
        ports:
            - '${LANCACHE_IP}:443:443'
        environment:
            - UPSTREAM_DNS=${DNS_SERVERS}
```
The .env file looks like this:
```
LANCACHE_IP=192.168.1.92
DNS_SERVERS="1.0.0.1 1.1.1.1"
CACHE_DISK_SIZE=1000G
CACHE_MEM_SIZE=500M
```
